# SwiftLint configuration for BehaviorTracker

included:
  - BehaviorTracker

excluded:
  - BehaviorTrackerTests
  - TrackerWidgets
  - BehaviorTracker/Models/*+CoreDataClass.swift
  - BehaviorTracker/Models/*+CoreDataProperties.swift

# Rules configuration
disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - nesting
  - identifier_name
  - modifier_order
  - multiple_closures_with_trailing_closure
  - implicit_optional_initialization

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - yoda_condition

# Custom rules
force_cast: warning
force_try: warning
force_unwrapping: warning

# Type rules
type_name:
  min_length: 2
  max_length: 50

# Function parameter count
function_parameter_count:
  warning: 8
  error: 10

# Large tuples
large_tuple:
  warning: 3
  error: 4

reporter: "xcode"
